### ISSUE TITLE
Impossibile installare plugin Movecost

### ISSUE THREAD

**Issue by ManuPutti** [enzococca/movecostTOqgis#1]
Utilizzando l'ultima LTR di Qgis (3.16.11-Hannover) non riesco in alcun modo ad installare il plugin ottenendo sempre questo messaggio di errore. Ho provato a reinstallare qgis con privilegi di amministratore ed aprirlo, sempre come amministratore ma non ho risolto

Impossibile caricare il plugin 'movecost' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\__init__.py", line 35, in classFactory
    from .movecost import MOVECOST
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\movecost.py", line 31, in 
    from .movecost_dialog import MOVECOSTDialog
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\movecost_dialog.py", line 39, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 92, in 
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.16.11-Hannover Hannover, 26cc1c76 

Percorso Python:
C:/PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python
C:/Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.16.11\bin\python39.zip
C:\PROGRA~1\QGIS31~1.11\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib
C:\Program Files\QGIS 3.16.11\bin
C:\PROGRA~1\QGIS31~1.11\apps\Python39
C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by ManuPutti** [comment]
No purtroppo mi da lo stesso errore

2021-10-21T14:10:39     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\__init__.py", line 35, in classFactory
              from .movecost import MOVECOST
              File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\movecost.py", line 31, in 
              from .movecost_dialog import MOVECOSTDialog
              File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Msi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\movecost\movecost_dialog.py", line 39, in 
              FORM_CLASS, _ = uic.loadUiType(os.path.join(
              File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
              return __PyQtLoadUiType(*args, **kwargs)
              File "C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
              exec(code_string.getvalue(), ui_globals)
              File "", line 92, in 
              File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'resources_rc'
